【try-catch-finallyについて】

try
try内で例外が起こった場合、catchに処理が移る。
例外が起こった瞬間にtry内の処理が終わってしまうので、１行目で例外が起きれば２行目は処理されない。

catch　型がエラー　引数がe（eではなくてもいいけど）
型はtryで起こりうるエラーの型にしておく必要がある。

finally
書かなくても別にいい。書いたら例外が起きても怒らなくても必ず実行される。


throwsについて
